BettingWebSiteBackEnd/Models/ErrorViewModel.cs
namespace BettingWebSiteBackEnd.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BettingWebSiteBackEnd/Controllers/AddMoneyController.cs
using BettingWebSiteBackEnd.Consumers;
using MassTransit;
using MassTransit.Testing;
using Microsoft.AspNetCore.Mvc;
using Shared.Events;

namespace BettingWebSiteBackEnd.Controllers
{
    public class AddMoneyController : Controller
    {
        private readonly IPublishEndpoint publishEndpoint;

        public AddMoneyController(IPublishEndpoint publishEndpoint)
        {
            this.publishEndpoint = publishEndpoint;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(MoneyIncreaseEvent x)
        {
            x.WhiceSide = Shared.Enums.MoneyTransactionEnum.plus;
            MailGetEventRequest mailGetEventRequest = new()
            {
                Tc = x.Tc
            };
            await publishEndpoint.Publish(mailGetEventRequest);
            await Task.Delay(6000);
            MailSentEvent mailSentEvent = new()
            {
                EMail = MailGetEventResponseConsumer.Email,
                Price = int.Parse(x.Money),
                State = Shared.Enums.MailEnum.MoneyAdd
            };
            await publishEndpoint.Publish(mailSentEvent);
            MoneyIncreaseEvent moneyIncreaseEvent = x;
             await  publishEndpoint.Publish(moneyIncreaseEvent);
            return View();
        }
    }
}

BettingWebSiteBackEnd/Controllers/CouponsController.cs
using BettingWebSiteBackEnd.Consumers;
using MassTransit;
using Microsoft.AspNetCore.Mvc;
using Shared.Events;

namespace BettingWebSiteBackEnd.Controllers
{
    public class CouponsController : Controller
    {
        private readonly IPublishEndpoint publishEndpoint;
       
        public CouponsController(IPublishEndpoint publishEndpoint)
        {
            this.publishEndpoint = publishEndpoint;
        }

        public IActionResult Index()
        {
            OrderGetEventResponseEvent orderGetEventResponsecshtml = new();
            if (OrderGetEventResponseEventConsumer.orderGetEventResponseEvent != null) {
               orderGetEventResponsecshtml = OrderGetEventResponseEventConsumer.orderGetEventResponseEvent; }
            else {
                orderGetEventResponsecshtml.OrderGetEventId = "boş ";
                orderGetEventResponsecshtml.coupunContents.Add(new() 
                { PaidMoney = "0",
                state= Shared.Enums.StateEnum.failed,
               TotalMoney="0",
               TotalRate="0",
               orderContentContents = new() { new()
               {
                    Tc ="0",
                    Team1 = "0",
                    Team2 = "0",
                    MatchSide = Shared.Enums.MatchSideEnum.ms0
               } }
                }  
                );
            }
           
            return View(orderGetEventResponsecshtml);
        }
        [HttpPost]
        public async Task<IActionResult> CouponsOkey(string Tc,string TotalMoney,string TotalRate)
        {
            MoneyIncreaseEvent moneyIncreaseEvent = new()
            {
                Money = TotalMoney,
                Tc = Tc,
                WhiceSide = Shared.Enums.MoneyTransactionEnum.plus
            };
            CouponComplatedEvent couponComplatedEvent = new() {
            Tc = Tc,
            TotalMoney = TotalMoney,
            TotalRate = TotalRate
            };
            MailGetEventRequest mailGetEventRequest = new()
            {
                Tc = Tc
            };
            await publishEndpoint.Publish(mailGetEventRequest);
            await Task.Delay(6000);
            MailSentEvent mailSentEvent = new()
            {
                EMail = MailGetEventResponseConsumer.Email,
                Price = int.Parse(TotalMoney),
                State = Shared.Enums.MailEnum.MoneyAdd
            };
            await publishEndpoint.Publish(mailSentEvent);
            await publishEndpoint.Publish(moneyIncreaseEvent);
            await publishEndpoint.Publish(couponComplatedEvent);
            return RedirectToAction("Index", "Home", new { Area = "" });
        }
        
        [HttpPost]
        public async Task<IActionResult> CouponsDenied(string Tc, string TotalMoney, string TotalRate)
        {
            CouponFailedEvent couponFailedEvent = new()
            {
                Tc=Tc,
                TotalMoney=TotalMoney,
                TotalRate=TotalRate
            };
            await publishEndpoint.Publish(couponFailedEvent);

            return RedirectToAction("Index", "Home", new { Area = "" });
        }
    }
}

BettingWebSiteBackEnd/Controllers/HomeController.cs
using BettingWebSiteBackEnd.Models;
using MassTransit;
using Microsoft.AspNetCore.Mvc;
using Shared.Events;
using System.Diagnostics;

namespace BettingWebSiteBackEnd.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IPublishEndpoint publishEndpoint;

        public HomeController(ILogger<HomeController> logger,IPublishEndpoint publishEndpoint)
        {
            _logger = logger;
            this.publishEndpoint = publishEndpoint;
        }

        public async Task<IActionResult> Index()
        {
            OrderGetEventRequest orderGetEventRequest = new OrderGetEventRequest()
            {
                OrderGetEventId = Guid.NewGuid().ToString(),
            };
           await publishEndpoint.Publish(orderGetEventRequest);
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BettingWebSiteBackEnd/Controllers/MinusMoneyController.cs
using BettingWebSiteBackEnd.Consumers;
using MassTransit;
using Microsoft.AspNetCore.Mvc;
using Shared.Events;

namespace BettingWebSiteBackEnd.Controllers
{
    public class MinusMoneyController : Controller
    {
        private readonly IPublishEndpoint publishEndpoint;

        public MinusMoneyController(IPublishEndpoint publishEndpoint)
        {
            this.publishEndpoint = publishEndpoint;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Index(MoneyDecreaseEvent x)
        {
            x.WhiceSide = Shared.Enums.MoneyTransactionEnum.minus;


            MoneyDecreaseEvent DecreaseEvent = x;
            await publishEndpoint.Publish(DecreaseEvent);
            return View();
        }
    }
}

BettingWebSiteBackEnd/Views/AddMoney/Index.cshtml
@using Shared.Events
@model MoneyIncreaseEvent
<form id="moneyIncreaseForm" asp-action="Index" method="post">
    <div class="form-container" style="overflow: hidden;">
        <div class="form-group" style="margin-right: 50px; margin-left: 50px; text-align: center;">
            <label style="display: block; margin: 0 auto; width: fit-content;">Kullanıcıya Para Ekle</label>
        </div>
        <div class="form-group" style="margin-right: 50px; margin-left: 50px;">
            <label for="tc">TC:</label>
            <input type="text" class="form-control" id="tc" name="Tc" maxlength="11">
            <div id="tcError" class="text-danger"></div>
        </div>
        <div class="form-group" style="margin-right: 50px; margin-left: 50px;">
            <label for="money">Para(eklenecek para dolar olacaktır):</label>
            <input type="text" class="form-control" id="money" name="Money">
        </div>
        <button type="submit" class="btn btn-primary" style="margin-right: 50px; margin-left: 50px;">Gönder</button>
    </div>
</form>


<script>
    document.getElementById("moneyIncreaseForm").addEventListener("submit", function (event) {
        var tcInput = document.getElementById("tc");
        var tcValue = tcInput.value.trim();

        if (tcValue.length !== 11 || isNaN(tcValue)) {
            event.preventDefault();
            document.getElementById("tcError").innerText = "TC kimlik numarası 11 haneli olmalıdır.";
        } else {
            document.getElementById("tcError").innerText = "";
            // Başarılı gönderim durumunda alert göster
            alert("Gönderildi");
        }
    });
</script>

BettingWebSiteBackEnd/Views/Coupons/Index.cshtml
@using Shared.Events
@model OrderGetEventResponseEvent;

<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bekleyen Kuponlar</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
            margin: 0;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th, td {
            padding: 8px;
            border: 1px solid #ddd;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }

        .btn {
            padding: 10px 20px;
            font-size: 16px;
            cursor: pointer;
            background-color: #007BFF;
            color: #fff;
            border: none;
            border-radius: 5px;
        }

            .btn:hover {
                background-color: #0056b3;
            }

        .alert-container {
            display: none;
            position: fixed;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            padding: 20px;
            width: 80%; /* Genişletme */
            max-height: 80%; /* Yükseklik */
            overflow: auto; /* Scroll */
            background-color: #f8d7da;
            border: 1px solid #f5c6cb;
            border-radius: 5px;
            color: #721c24;
            z-index: 9999; /* En üstte */
        }

            .alert-container.show {
                display: block;
            }
    </style>
</head>
<body>

    <table>
        <thead>
            <tr>
                <th>Ödenen Tutar</th>
                <th>Toplam Kazanç</th>
                <th>Durum</th>
                <th>Toplam Oran</th>
                <th>Kontrol Et</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var x in Model.coupunContents)
            {
                <tr>
                    <td>@x.PaidMoney</td>
                    <td>@x.TotalMoney</td>
                    <td>@x.state</td>
                    <td>@x.TotalRate</td>
                    <td>
                        @foreach(var c in x.orderContentContents)
                        {
                            <button type="button" class="btn btn-primary" onclick="showAlert('@c.Tc', '@c.Team1', '@c.Team2', '@c.MatchSide')">Kontrol Et</button>
                        }
                       
                    </td>

                    <td>
                        <form asp-action="CouponsOkey" asp-controller="Coupons" method="post">
                            <input type="hidden" name="Tc" value="@x.orderContentContents.FirstOrDefault().Tc" />
                            <input type="hidden" name="TotalMoney" value="@x.TotalMoney" />
                            <input type="hidden" name="TotalRate" value="@x.TotalRate" />
                            <!-- Diğer gizli alanlar için gerekli bilgileri ekleyin -->
                            <button type="submit" style="background-color:forestgreen">Kupon Onayla</button>
                        </form>
                    </td>

                    <td>
                        <form asp-action="CouponsDenied" asp-controller="Coupons" method="post">
                            <input type="hidden" name="Tc" value="@x.orderContentContents.FirstOrDefault().Tc" />
                            <input type="hidden" name="TotalMoney" value="@x.TotalMoney" />
                            <input type="hidden" name="TotalRate" value="@x.TotalRate" />
                            <!-- Diğer gizli alanlar için gerekli bilgileri ekleyin -->
                            <button type="submit" style="background-color:red">Kupon Reddet</button>
                        </form>
                    </td>

                </tr>
            }
        </tbody>
    </table>

    <div id="alertContainer" class="alert-container">
        <div class="alert">
            <table id="alertTable">
                <thead>
                    <tr>
                        <th>Tc</th>
                        <th>Team1</th>
                        <th>Team2</th>
                        <th>Match Side</th>
                    </tr>
                </thead>
                <tbody id="alertTableBody">
                </tbody>
            </table>
            <button onclick="hideAlert()">Tamam</button>
        </div>
    </div>

    <script>
        function showAlert(Tc, Team1, Team2, MatchSide) {
            // Alert kutusunu göster
            var alertContainer = document.getElementById('alertContainer');
            alertContainer.classList.add('show');

            // Alert kutusuna detayları ekle
            var alertTableBody = document.getElementById('alertTableBody');
            alertTableBody.innerHTML = '';

            // Verileri ekle
            var newRow = alertTableBody.insertRow();
            newRow.insertCell().innerText = Tc;
            newRow.insertCell().innerText = Team1;
            newRow.insertCell().innerText = Team2;
            newRow.insertCell().innerText = MatchSide;
        }

        function hideAlert() {
            // Alert kutusunu gizle
            var alertContainer = document.getElementById('alertContainer');
            alertContainer.classList.remove('show');
        }
    </script>

</body>
</html>

BettingWebSiteBackEnd/Views/Home/Index.cshtml
@* @{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Admim Panele Hoşgeldiniz</h1>
    <p> Kumar Yuva YIKAR.....</p>
</div>
 *@
@{
    ViewData["Title"] = "Admin Paneli";
}
<div class="container text-center">
    <div class="row">
        <div class="col">
            <img src="~/dur_logo.jpg" alt="Admin Logo" class="img-fluid mt-5" style="max-width: 200px;">
            <p style="color: red; font-size: 24px;">DUR BET</p>
            <h1 class="display-4 mt-3">Admin Paneline Hoşgeldiniz</h1>
            <p class="lead">Kumar Yuva YIKAR.....</p>
        </div>
    </div>
</div>

BettingWebSiteBackEnd/Views/MinusMoney/Index.cshtml
@using Shared.Events
@model MoneyDecreaseEvent
<form id="moneyIncreaseForm" asp-action="Index" method="post">
    <div class="form-container" style="overflow: hidden;">
        <div class="form-group" style="margin-right: 50px; margin-left: 50px; text-align: center;">
            <label style="display: block; margin: 0 auto; width: fit-content;">Kullanıcıdan Para Eksilt</label>
        </div>
        <div class="form-group" style="margin-right: 50px; margin-left: 50px;">
            <label for="tc">TC:</label>
            <input type="text" class="form-control" id="tc" name="Tc" maxlength="11">
            <div id="tcError" class="text-danger"></div>
        </div>
        <div class="form-group" style="margin-right: 50px; margin-left: 50px;">
            <label for="money">Para(eklenecek para dolar olacaktır):</label>
            <input type="text" class="form-control" id="money" name="Money">
        </div>
        <button type="submit" class="btn btn-primary" style="margin-right: 50px; margin-left: 50px;">Eksilt</button>
    </div>
</form>

<div style="background-color: #ffe6e6; color: #cc0000; padding: 10px; border: 2px solid #cc0000; border-radius: 5px;">
    <strong>Uyarı:</strong> Kullanıcı parasından büyük eksiltmelerde, kullanıcı bakiyesi sıfırlanır  eksiye düşmez!
</div>



<script>
    document.getElementById("moneyIncreaseForm").addEventListener("submit", function (event) {
        var tcInput = document.getElementById("tc");
        var tcValue = tcInput.value.trim();

        if (tcValue.length !== 11 || isNaN(tcValue)) {
            event.preventDefault();
            document.getElementById("tcError").innerText = "TC kimlik numarası 11 haneli olmalıdır.";
        } else {
            document.getElementById("tcError").innerText = "";
            // Başarılı gönderim durumunda alert göster
            alert("Gönderildi");
        }
    });
</script>

BettingWebSiteBackEnd/Views/Shared/_Layout.cshtml
<!DOCTYPE html>


<html lang="en" class="light-style layout-menu-fixed layout-compact " dir="ltr" data-theme="theme-default" data-template="vertical-menu-template-free">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />


    <title>Süper Admin Panel</title>


    <!-- Font Awesome CSS dosyasını projenize ekleyin -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-xBu4H2Kje6z1XvWUG8fZP3tgoUStlBYkQ5P/L4aDkFJ6q2BCz3xmUHkw+beMv2l/9aYlMmeNk5+ogrk61DvPjA==" crossorigin="anonymous" />


    <meta name="description" content="Most Powerful &amp; Comprehensive Bootstrap 5 HTML Admin Dashboard Template built for developers!" />
    <meta name="keywords" content="dashboard, bootstrap 5 dashboard, bootstrap 5 design, bootstrap 5">
    <!-- Canonical SEO -->
    <link rel="canonical" href="https://themeselection.com/item/sneat-bootstrap-html-admin-template/">


    <!-- ? PROD Only: Google Tag Manager (Default ThemeSelection: GTM-5DDHKGP, PixInvent: GTM-5J3LMKC) -->
    <script>
        (function (w, d, s, l, i) {
            w[l] = w[l] || []; w[l].push({
                'gtm.start':
                    new Date().getTime(), event: 'gtm.js'
            }); var f = d.getElementsByTagName(s)[0],
                j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src =
                    'https://www.googletagmanager.com/gtm.js?id=' + i + dl; f.parentNode.insertBefore(j, f);
        })(window, document, 'script', 'dataLayer', 'GTM-5DDHKGP');</script>
    <!-- End Google Tag Manager -->
    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">


    <link rel="stylesheet" href="~/sneat-1.0.0/assets/vendor/fonts/boxicons.css" />


    <!-- Core CSS -->
    <link rel="stylesheet" href="~/sneat-1.0.0/assets/vendor/css/core.css" class="template-customizer-core-css" />
    <link rel="stylesheet" href="~/sneat-1.0.0/assets/vendor/css/theme-default.css" class="template-customizer-theme-css" />
    <link rel="stylesheet" href="~/sneat-1.0.0/assets/css/demo.css" />

    <!-- Vendors CSS -->
    <link rel="stylesheet" href="~/sneat-1.0.0/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css" />
    <link rel="stylesheet" href="~/sneat-1.0.0/assets/vendor/libs/apex-charts/apex-charts.css" />

    <!-- Page CSS -->
    <!-- Helpers -->
    <script src="~/sneat-1.0.0/assets/vendor/js/helpers.js"></script>
    <!--! Template customizer & Theme config files MUST be included after core stylesheets and helpers.js in the <head> section -->
    <!--? Config:  Mandatory theme config file contain global vars & default theme options, Set your preferred theme option in this file.  -->
    <script src="~/sneat-1.0.0/assets/js/config.js"></script>
    @*  @RenderSection("Scripts", required: false) *@
</head>

<body>


    <!-- ?PROD Only: Google Tag Manager (noscript) (Default ThemeSelection: GTM-5DDHKGP, PixInvent: GTM-5J3LMKC) -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-5DDHKGP" height="0" width="0" style="display: none; visibility: hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->
    <!-- Layout wrapper -->
    <div class="layout-wrapper layout-content-navbar  ">
        <div class="layout-container">







            <!-- Menu -->

            <aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">


                <div class="app-brand demo ">
                    <a asp-action="Index" asp-controller="Home" target="_self" class="app-brand-link">


                        <span class="app-brand-text demo menu-text fw-bold ms-2">Admin Panel</span>
                    </a>

                    <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
                        <i class="bx bx-chevron-left bx-sm align-middle"></i>
                    </a>
                </div>

                <div class="menu-inner-shadow"></div>



                <ul class="menu-inner py-1">

                    <!--home page -->
                    <li class="menu-item active open">
                        <a href="javascript:void(0);" class="menu-link menu-toggle">
                            <i class="menu-icon tf-icons bx bx-home-circle"></i>
                            <div data-i18n="Dashboards">Home Page</div>

                        </a>
                        <ul class="menu-sub">
                            <li class="menu-item active">
                                <a asp-action="Index" asp-controller="Home" target="_self" class="menu-link">
                                    <div data-i18n="CRM">Home Page</div><div class="badge bg-label-primary fs-tiny rounded-pill ms-auto">Ana Sayfa</div>
                                </a>
                            </li>
                            <li class="menu-item">
                                <a asp-action="Index" asp-controller="Coupons" target="_self" class="menu-link">
                                    <div data-i18n="Analytics">Onay Veya Red Bekleyen Kuponlar</div>
                                </a>
                            </li>
                            <li class="menu-item">
                                <a asp-action="Index" asp-controller="AddMoney" target="_self" class="menu-link">
                                    <div data-i18n="eCommerce" >Kullanıcıya Para Ekle</div>
                                </a>
                            </li>

                            <li class="menu-item">
                                <a asp-action="Index" asp-controller="MinusMoney" target="_self" class="menu-link">
                                    <div data-i18n="eCommerce">Kullanıcıdan Para Eksilt</div>
                                </a>
                            </li>

                        </ul>
                    </li>








                </ul>


            </aside>
            <!-- / Menu -->
            <!-- Layout container -->
            <div class="layout-page">





                <!-- Navbar -->




                <nav class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme" id="layout-navbar">


                    <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0   d-xl-none ">
                        <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
                            <i class="bx bx-menu bx-sm"></i>
                        </a>
                    </div>


                    <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">



                        <ul class="navbar-nav flex-row align-items-center ms-auto">


                            <!-- User -->
                            <li class="nav-item navbar-dropdown dropdown-user dropdown">
                                <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
                                    <div class="avatar avatar-online">
                                        <img src="~/sneat-1.0.0/assets/img/avatars/1.png" alt class="w-px-40 h-auto rounded-circle">
                                    </div>
                                </a>
                                <ul class="dropdown-menu dropdown-menu-end">
                                    <li>
                                        <a class="dropdown-item" href="#">
                                            <div class="d-flex">
                                                <div class="flex-shrink-0 me-3">
                                                    <div class="avatar avatar-online">
                                                        <img src="~/sneat-1.0.0/assets/img/avatars/1.png" alt class="w-px-40 h-auto rounded-circle">
                                                    </div>
                                                </div>
                                                <div class="flex-grow-1">
                                                    <span class="fw-medium d-block">ADMIN</span>
                                                    <small class="text-muted">Admin</small>
                                                </div>
                                            </div>
                                        </a>
                                    </li>
                                    <li>
                                        <div class="dropdown-divider"></div>
                                    </li>

                                    <li>
                                        <a class="dropdown-item" href="javascript:void(0);">

                                            <form method="get" asp-controller="Auth" asp-action="Logout">
                                                <i class="bx bx-power-off me-2"></i>
                                                <button class="align-middle" type="submit">Çıkış Yap</button>
                                                @* <span class="align-middle">Log Out</span> *@
                                            </form>

                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <!--/ User -->


                        </ul>
                    </div>
                    @*
                    asp-action="Index" asp-controller="Home" asp-area ="" *@

                </nav>


                <!-- Content wrapper -->
                <div>

                    @RenderBody()

                </div>
                <!-- Content wrapper -->
            </div>
            <!-- / Layout page -->
        </div>



        <!-- Overlay -->
        <div class="layout-overlay layout-menu-toggle"></div>


    </div>
    <!-- / Layout wrapper -->
    <!-- Core JS -->
    <!-- build:js assets/vendor/js/core.js -->

    <script src="~/sneat-1.0.0/assets/vendor/libs/jquery/jquery.js"></script>
    <script src="~/sneat-1.0.0/assets/vendor/libs/popper/popper.js"></script>
    <script src="~/sneat-1.0.0/assets/vendor/js/bootstrap.js"></script>
    <script src="~/sneat-1.0.0/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>
    <script src="~/sneat-1.0.0/assets/vendor/js/menu.js"></script>

    <!-- endbuild -->
    <!-- Vendors JS -->
    <script src="~/sneat-1.0.0/assets/vendor/libs/apex-charts/apexcharts.js"></script>

    <!-- Main JS -->
    <script src="~/sneat-1.0.0/assets/js/main.js"></script>


    <!-- Page JS -->
    <script src="~/sneat-1.0.0/assets/js/dashboards-analytics.js"></script>

    <!-- Place this tag in your head or just before your close body tag. -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>

</body>

</html>