BettingWebSiteFUserInterface/Areas/Auth/Controllers/Auth1Controller.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using BettingWebSiteFUserInterface.Models;
using Shared.Events;
using MassTransit;
using BettingWebSiteFUserInterface.Consumers;

namespace BettingWebSiteFUserInterface.Areas.Auth.Controllers
{
    [Area("Auth")]
    [Authorize]
    public class Auth1Controller : Controller
    {
        private readonly IPublishEndpoint publishEndpoint;
        public static UserLoginCheckEvent userLoginCheckEventstatic = new();
        public Auth1Controller(IPublishEndpoint publishEndpoint)
        {
            this.publishEndpoint = publishEndpoint;
        }

        public IActionResult Index()
        {
            return View();
        }
        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> Login()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> Login(UserLoginCheck userLoginCheck)
        {
          

            if (userLoginCheck != null)
            {
                userLoginCheckEventstatic.Tc = userLoginCheck.Tc;
                userLoginCheckEventstatic.Password = userLoginCheck.Password;
                await publishEndpoint.Publish(userLoginCheckEventstatic);
                await Task.Delay(8000);
                if (UserLoginCheckEventConsumer.IsValid)
                {
                    var claims = new List<Claim>
                          {
                          new Claim("tc",userLoginCheck.Tc)
                       // Daha fazla kullanıcı bilgisi ekleyebilirsiniz.
                       

                           };
                    //    // Kimlik oluşturma
                    var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                    // Kimlik oluşturup kullanıcıyı giriş yapmış olarak işaretleme
                    var principal = new ClaimsPrincipal(identity);
                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);

                    return RedirectToAction("Index", "Home", new { Area = "" });
                }
                
            }
            return View();
        
        }



        [AllowAnonymous]
        public IActionResult Logout()
        {
            return RedirectToAction("Index", "Home", new { Area = "" });
        }
    }
}

BettingWebSiteFUserInterface/Views/Shared/_Layout.cshtml
@using BettingWebSiteFUserInterface.Areas.Auth.Controllers
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BettingWebSiteFUserInterface</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BettingWebSiteFUserInterface.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="color:red">DUR BET</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>


                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Ana Sayfa</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="LoadPay">Para Yükle</a>
                        </li>
                    </ul>
                 

                    <div id="totalPrice">
                        Cüzdanım: @Auth1Controller.userLoginCheckEventstatic.TotalPrice $
                    </div>
                  
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Sepet" asp-area="">Sepet</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-action="Logout" asp-controller="Auth1" asp-area="Auth">Log Out</a>
                        </li>
                    </ul>
                </div>
            </div>

   
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
          2024 - DUR BET - 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>